######################################################################
# Automatically generated by qmake (3.1) Thu Dec 28 04:06:30 2023
######################################################################

TEMPLATE = app
TARGET = plug-test
INCLUDEPATH += .
CONFIG += console

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
LIBS += `pkg-config opencv4 --libs`
QMAKE_CXXFLAGS += -O3 `pkg-config opencv4 --cflags`
SOURCES += plug-test.cpp ../plugin_program.cpp
HEADERS += ../plugin_program.hpp
